// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boynzjdotukumxrpfoxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveW56amRvdHVrdW14cnBmb3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTc2MTksImV4cCI6MjA3MjY5MzYxOX0.rr6KVa_lJFNihTmJd6HyqqhGKgA-2LkAnyHfovLP1c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});